# Generated by Django 4.1.7 on 2023-03-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
