# Generated by Django 4.1.7 on 2023-03-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('б/у', 'Б/У'), ('Новый', 'Новый')], max_length=50, null=True),
        ),
    ]
