# Generated by Django 4.1.7 on 2023-03-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, choices=[('Синий', 'Cиний'), ('Красный', 'Красный')], max_length=50, null=True),
        ),
    ]
